/* desktop_downloads_top25_rules.yar
   Top-25 static YARA rules for downloaded desktop files
   Format: F1 (25 standalone rules)
   Certificate detection: Light (issuer substring checks)
   Author: placeholder (Generated by ChatGPT)
   Version: 1.0
*/

rule PE_Suspicious_Section_Names
{
    meta:
        severity = 8
        kill_chain = "execution"
        malware_class = "loader/dropper"
        file_type = "PE"
        description = "PE with suspicious or non-standard section names often used by packers/obfuscators."
        version = "1.0"
        author = "ChatGPT (placeholder)"
    strings:
        $sec1 = ".gaga"
        $sec2 = ".xyz"
        $sec3 = ".textbss"
        $sec4 = ".upx0"
        $sec5 = ".stub"
    condition:
        uint16(0) == 0x5A4D and (any of ($sec*))
}

rule PE_Packed_UPX_Modified
{
    meta:
        severity = 9
        kill_chain = "defense-evasion"
        malware_class = "packed"
        file_type = "PE"
        description = "UPX packing signature combined with tampered or nonstandard UPX stub."
        version = "1.0"
        author = "ChatGPT (placeholder)"
    strings:
        $upx_marker = "UPX!" nocase
        $upx_stub = "UPX0" nocase
    condition:
        uint16(0) == 0x5A4D and $upx_marker and filesize < 50MB
}

rule PE_Anti_VM_Strings
{
    meta:
        severity = 7
        kill_chain = "reconnaissance/defense-evasion"
        malware_class = "evasion"
        file_type = "PE"
        description = "Presence of common VM/Sandbox strings within PE resources or strings."
        version = "1.0"
        author = "ChatGPT (placeholder)"
    strings:
        $a1 = "VBox" ascii wide
        $a2 = "VMware" ascii wide
        $a3 = "qemu" ascii wide
        $a4 = "Sandboxie" ascii wide
        $a5 = "VirtualBox" ascii wide
    condition:
        uint16(0) == 0x5A4D and any of ($a*)
}

rule PE_Process_Injection_APIs
{
    meta:
        severity = 10
        kill_chain = "execution/persistence"
        malware_class = "injector/RAT"
        file_type = "PE"
        description = "PE importing classic process injection APIs."
        version = "1.0"
        author = "ChatGPT (placeholder)"
    strings:
        $s1 = "VirtualAlloc" ascii
        $s2 = "WriteProcessMemory" ascii
        $s3 = "CreateRemoteThread" ascii
        $s4 = "NtProtectVirtualMemory" ascii
    condition:
        uint16(0) == 0x5A4D and pe.imports("kernel32.dll", "VirtualAlloc") or
        uint16(0) == 0x5A4D and (any of ($s*))
}

rule PE_Keylogger_APIs
{
    meta:
        severity = 8
        kill_chain = "collection"
        malware_class = "keylogger/stealer"
        file_type = "PE"
        description = "PE referencing keyboard hook or key state APIs typical for keyloggers."
        version = "1.0"
        author = "ChatGPT (placeholder)"
    strings:
        $k1 = "SetWindowsHookEx" ascii
        $k2 = "GetAsyncKeyState" ascii
        $k3 = "keybd_event" ascii
    condition:
        uint16(0) == 0x5A4D and any of ($k*)
}

rule PE_Credential_Theft_APIs
{
    meta:
        severity = 9
        kill_chain = "collection/exfiltration"
        malware_class = "stealer"
        file_type = "PE"
        description = "APIs used to access protected credentials or enumerate logon sessions."
        version = "1.0"
        author = "ChatGPT (placeholder)"
    strings:
        $c1 = "CryptUnprotectData" ascii
        $c2 = "LsaEnumerateLogonSessions" ascii
        $c3 = "CredEnumerate" ascii
        $c4 = "WNetEnumCachedPasswords" ascii
    condition:
        uint16(0) == 0x5A4D and any of ($c*)
}

rule PE_Ransomware_Extension_Strings
{
    meta:
        severity = 10
        kill_chain = "impact"
        malware_class = "ransomware"
        file_type = "PE"
        description = "Embedded strings indicating ransom extension or marker usage."
        version = "1.0"
        author = "ChatGPT (placeholder)"
    strings:
        $r1 = ".locked" nocase
        $r2 = ".encrypted" nocase
        $r3 = ".darkfail" nocase
        $r4 = "!!!README" nocase
    condition:
        uint16(0) == 0x5A4D and any of ($r*)
}

rule PE_Embedded_Ransom_Note
{
    meta:
        severity = 10
        kill_chain = "impact"
        malware_class = "ransomware"
        file_type = "PE"
        description = "Common ransom note phrases embedded in binary or resources."
        version = "1.0"
        author = "ChatGPT (placeholder)"
    strings:
        $n1 = "Your files have been encrypted" ascii nocase
        $n2 = "recover key" ascii nocase
        $n3 = "payment to" ascii nocase
    condition:
        uint16(0) == 0x5A4D and any of ($n*)
}

rule PE_Crypto_Clipboard_Hijack
{
    meta:
        severity = 8
        kill_chain = "collection"
        malware_class = "crypto-stealer"
        file_type = "PE"
        description = "Patterns suggesting clipboard manipulation for cryptocurrency address replacement."
        version = "1.0"
        author = "ChatGPT (placeholder)"
    strings:
        $w1 = "clipboard" ascii nocase
        $w2 = "wallet" ascii nocase
        $w3 = "0x" ascii
        $regex_wallet = /\b(0x[a-fA-F0-9]{30,70})\b/
    condition:
        uint16(0) == 0x5A4D and (any of ($w*) or $regex_wallet)
}

rule PE_C2_URL_Patterns
{
    meta:
        severity = 9
        kill_chain = "command-and-control"
        malware_class = "RAT/stealer/backdoor"
        file_type = "PE"
        description = "Embedded remote endpoints and known gate-like paths."
        version = "1.0"
        author = "ChatGPT (placeholder)"
    strings:
        $u1 = "/gate.php" ascii nocase
        $u2 = "/panel/" ascii nocase
        $u3 = "/upload.php" ascii nocase
        $u4 = "/connect.php" ascii nocase
        $http = "http://" ascii
        $https = "https://" ascii
    condition:
        uint16(0) == 0x5A4D and any of ($u*) and ( $http or $https )
}

rule PE_DGA_Domain_Heuristics
{
    meta:
        severity = 8
        kill_chain = "command-and-control"
        malware_class = "RAT/DGA"
        file_type = "PE"
        description = "Heuristic detection of DGA-like domains embedded in resources (random letter patterns)."
        version = "1.0"
        author = "ChatGPT (placeholder)"
    strings:
        $dga1 = /[a-z]{8,}\.(com|net|top|xyz|ru|pw)/ nocase
    condition:
        uint16(0) == 0x5A4D and any of ($dga1)
}

rule PE_Powershell_Stage_In_Resources
{
    meta:
        severity = 9
        kill_chain = "execution/initial-access"
        malware_class = "dropper/unpacker"
        file_type = "PE"
        description = "Base64 PowerShell command found inside resources or data segments."
        version = "1.0"
        author = "ChatGPT (placeholder)"
    strings:
        $ps_pref = "powershell -enc " ascii nocase
        $ps_b64 = /[A-Za-z0-9+\/]{100,}={0,2}/
    condition:
        uint16(0) == 0x5A4D and ( $ps_pref or $ps_b64 )
}

rule Archive_Double_Extension_Trap
{
    meta:
        severity = 9
        kill_chain = "initial-access"
        malware_class = "phishing/dropper"
        file_type = "archive"
        description = "Archive entries that use double extensions (e.g., .pdf.exe) used heavily in phishing."
        version = "1.0"
        author = "ChatGPT (placeholder)"
    strings:
        $d1 = ".pdf.exe" ascii nocase
        $d2 = ".jpg.scr" ascii nocase
        $d3 = ".docx.vbs" ascii nocase
        $d4 = ".doc.lnk" ascii nocase
    condition:
        for any of ($d*) : (filesize < 50MB and any of ($d*))
}

rule Office_AutoExec
{
    meta:
        severity = 9
        kill_chain = "execution"
        malware_class = "macro"
        file_type = "office"
        description = "Office documents using auto-execution macro entrypoints."
        version = "1.0"
        author = "ChatGPT (placeholder)"
    strings:
        $m1 = "AutoOpen" ascii nocase
        $m2 = "AutoClose" ascii nocase
        $m3 = "Document_Open" ascii nocase
        $m4 = "Workbook_Open" ascii nocase
    condition:
        ( uint32(0) == 0xE011CFD0 ) and ( any of ($m*) ) 
        /* Note: OLE2/CFB signature check for Office documents (.doc, .xls, .ppt, .docm, .xlsm, etc.) */
}

rule Office_Macro_Downloader_APIs
{
    meta:
        severity = 9
        kill_chain = "execution/command-and-control"
        malware_class = "macro/downloader"
        file_type = "office"
        description = "Macro code referencing network download APIs to fetch payloads at runtime."
        version = "1.0"
        author = "ChatGPT (placeholder)"
    strings:
        $o1 = "URLDownloadToFile" ascii nocase
        $o2 = "WinHttpRequest" ascii nocase
        $o3 = "Msxml2.XMLHTTP" ascii nocase
        $o4 = "CreateObject(\"WScript.Shell\"" ascii nocase
    condition:
        any of ($o*) and filesize < 10MB
}

rule Office_Cred_Theft_Logic
{
    meta:
        severity = 8
        kill_chain = "collection"
        malware_class = "macro/credential-theft"
        file_type = "office"
        description = "Macro automation referencing Outlook/Exchange objects or credential harvest logic."
        version = "1.0"
        author = "ChatGPT (placeholder)"
    strings:
        $oc1 = "Outlook.Application" ascii
        $oc2 = "GetCredentials" ascii nocase
        $oc3 = "Exchange" ascii nocase
    condition:
        any of ($oc*)
}

rule PDF_Embedded_JavaScript
{
    meta:
        severity = 9
        kill_chain = "execution"
        malware_class = "pdf-exploit"
        file_type = "pdf"
        description = "PDF containing JavaScript objects or launch actions."
        version = "1.0"
        author = "ChatGPT (placeholder)"
    strings:
        $p1 = "%PDF-" ascii
        $p2 = "/JS" ascii
        $p3 = "/JavaScript" ascii
        $p4 = "/OpenAction" ascii
        $p5 = "/Launch" ascii
    condition:
        $p1 at 0 and (any of ($p2, $p3, $p4, $p5))
}

rule PDF_Obfuscated_JavaScript
{
    meta:
        severity = 9
        kill_chain = "defense-evasion"
        malware_class = "pdf-exploit"
        file_type = "pdf"
        description = "PDF with heavily obfuscated JS (hex/unicode sequences)."
        version = "1.0"
        author = "ChatGPT (placeholder)"
    strings:
        $hex_seq = /\\x[0-9A-Fa-f]{2,}/
        $u_seq = /\\u[0-9A-Fa-f]{4,}/
    condition:
        "%PDF-" at 0 and (any of ($hex_seq, $u_seq))
}

rule PDF_Embedded_EXE
{
    meta:
        severity = 10
        kill_chain = "delivery"
        malware_class = "embedded-exe"
        file_type = "pdf"
        description = "PDF embedding an executable file stream (MZ header inside object stream)."
        version = "1.0"
        author = "ChatGPT (placeholder)"
    strings:
        $pdf = "%PDF-" ascii
        $mz = "MZ" ascii
        $ef = "/EmbeddedFile" ascii
    condition:
        $pdf at 0 and $ef and $mz
}

rule Script_PS1_Base64_Loader
{
    meta:
        severity = 9
        kill_chain = "execution"
        malware_class = "script/loader"
        file_type = "ps1"
        description = "PowerShell Base64 encoded payload commonly used for initial access or staging."
        version = "1.0"
        author = "ChatGPT (placeholder)"
    strings:
        $pref = "powershell -EncodedCommand" ascii nocase
        $b64 = /[A-Za-z0-9+\/]{100,}={0,2}/
    condition:
        any of ($pref, $b64) and filesize < 10MB
}

rule Script_Batch_Dropper
{
    meta:
        severity = 8
        kill_chain = "execution"
        malware_class = "dropper"
        file_type = "bat"
        description = "Batch or script patterns invoking downloader/execution helpers."
        version = "1.0"
        author = "ChatGPT (placeholder)"
    strings:
        $s1 = "bitsadmin" ascii nocase
        $s2 = "wmic process call create" ascii nocase
        $s3 = "wscript" ascii nocase
        $s4 = "powershell -enc" ascii nocase
    condition:
        any of ($s*)
}

rule MSI_CustomAction_Execs_Remote
{
    meta:
        severity = 8
        kill_chain = "execution"
        malware_class = "installer/loader"
        file_type = "msi"
        description = "MSI CustomAction invoking command lines or remote fetchers (PowerShell/cmd)."
        version = "1.0"
        author = "ChatGPT (placeholder)"
    strings:
        $c1 = "CustomAction" ascii nocase
        $c2 = "CmdLine" ascii nocase
        $c3 = "powershell.exe" ascii nocase
    condition:
        any of ($c1, $c2, $c3) and filesize < 200MB
}

rule ISO_LNK_Phishing_Combo
{
    meta:
        severity = 9
        kill_chain = "initial-access"
        malware_class = "phishing/dropper"
        file_type = "iso"
        description = "ISO containing LNK that points to bundled script or EXE — a popular desktop phishing delivery since macro restrictions."
        version = "1.0"
        author = "ChatGPT (placeholder)"
    strings:
        $iso_magic = "CD001" ascii  /* ISO9660 primary volume descriptor */
        $lnk_ext = ".lnk" ascii nocase
        $vbs = ".vbs" ascii nocase
        $ps1 = ".ps1" ascii nocase
    condition:
        $iso_magic and $lnk_ext and ( $vbs or $ps1 or "MZ" )
}

rule Signed_But_Suspicious_PE
{
    meta:
        severity = 8
        kill_chain = "defense-evasion"
        malware_class = "signed-malware"
        file_type = "PE"
        description = "PE that contains a digital signature whose issuer name matches known-abused or suspicious substrings (Light mode)."
        version = "1.0"
        author = "ChatGPT (placeholder)"
    strings:
        $iss1 = "WoSign" ascii nocase
        $iss2 = "StartCom" ascii nocase
        $iss3 = "Sectigo" ascii nocase
        $iss4 = "COMODO" ascii nocase
        $iss5 = "Test Certificate" ascii nocase
        $iss6 = "Expired" ascii nocase
    condition:
        uint16(0) == 0x5A4D and for any i in (1..5): (pe and pe.optional_header)
        and any of ($iss*)
        /* Note: This Light implementation searches for issuer substrings in the binary signature blob.
           For robust checks, integrate with an OS-level certificate parser at scan time. */
}

rule PE_Suspicious_Resource_Strings
{
    meta:
        severity = 7
        kill_chain = "reconnaissance"
        malware_class = "dropper/stealer"
        file_type = "PE"
        description = "Suspicious strings commonly embedded in resources (password, credential, panel)."
        version = "1.0"
        author = "ChatGPT (placeholder)"
    strings:
        $s1 = "password" ascii nocase
        $s2 = "username" ascii nocase
        $s3 = "token" ascii nocase
        $s4 = "panel" ascii nocase
    condition:
        uint16(0) == 0x5A4D and any of ($s*)
}

rule Archive_Contains_Single_Large_Encrypted_File
{
    meta:
        severity = 8
        kill_chain = "delivery"
        malware_class = "dropper"
        file_type = "archive"
        description = "Archive containing a single very large encrypted/opaque file and minimal metadata (common payload drop storage)."
        version = "1.0"
        author = "ChatGPT (placeholder)"
    condition:
        /* Orchestrator should provide file listing; fallback to heuristics: small archive with large binary blob */
        filesize > 1MB and filesize < 200MB and for any i in (0..0) : (1 == 1)
        /* Note: requires archive enumeration at scan time for best results */
}

rule PE_Shellcode_Stub_In_Rsrc
{
    meta:
        severity = 9
        kill_chain = "execution"
        malware_class = "exploit/loader"
        file_type = "PE"
        description = "MZ shellcode or small executable stub embedded in resources or data sections."
        version = "1.0"
        author = "ChatGPT (placeholder)"
    strings:
        $mz = "MZ" ascii
        $stub_pattern = { 60 89 E5 83 EC ? } /* generic prologue heuristic (may be noisy) */
    condition:
        uint16(0) == 0x5A4D and $mz and filesize < 50MB
}

rule PE_Suspicious_Import_Strings
{
    meta:
        severity = 8
        kill_chain = "execution"
        malware_class = "loader/backdoor"
        file_type = "PE"
        description = "Imports or strings referencing networking plus persistence APIs."
        version = "1.0"
        author = "ChatGPT (placeholder)"
    strings:
        $i1 = "RegSetValueEx" ascii
        $i2 = "CreateService" ascii
        $i3 = "WSAStartup" ascii
        $i4 = "InternetOpen" ascii
    condition:
        uint16(0) == 0x5A4D and any of ($i*)
}

rule PE_Packed_Stub_Generic
{
    meta:
        severity = 8
        kill_chain = "defense-evasion"
        malware_class = "packed"
        file_type = "PE"
        description = "Generic packed binary indicators: long XOR loops, repetitive NOP sleds, or short strings plus large binary blobs."
        version = "1.0"
        author = "ChatGPT (placeholder)"
    strings:
        $xor = /(\bfor\b|\bwhile\b).{0,200}xor/i
        $nop_sled = { 90 90 90 90 90 90 }
    condition:
        uint16(0) == 0x5A4D and ( $xor or $nop_sled )
}

rule PE_Persistence_Authority_Abuse
{
    meta:
        severity = 8
        kill_chain = "persistence"
        malware_class = "persistence"
        file_type = "PE"
        description = "Patterns indicating persistence mechanism usage (Run keys, Service creation, Scheduled tasks)."
        version = "1.0"
        author = "ChatGPT (placeholder)"
    strings:
        $r1 = "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run" ascii nocase
        $r2 = "CreateService" ascii
        $r3 = "schtasks.exe" ascii nocase
    condition:
        uint16(0) == 0x5A4D and any of ($r*)
}

rule PE_Potential_Script_Embedding
{
    meta:
        severity = 8
        kill_chain = "delivery"
        malware_class = "dropper"
        file_type = "PE"
        description = "PE containing obvious script payload snippets (.vbs, .ps1) embedded in resource streams."
        version = "1.0"
        author = "ChatGPT (placeholder)"
    strings:
        $vbs = ".vbs" ascii nocase
        $ps1 = ".ps1" ascii nocase
        $js = ".js" ascii nocase
    condition:
        uint16(0) == 0x5A4D and any of ($vbs, $ps1, $js)
}

rule PE_Command_Execution_APIs
{
    meta:
        severity = 8
        kill_chain = "execution/command-and-control"
        malware_class = "RAT/dropper"
        file_type = "PE"
        description = "Usage of APIs to spawn shells or execute system commands (CreateProcess, system, WinExec)."
        version = "1.0"
        author = "ChatGPT (placeholder)"
    strings:
        $c1 = "CreateProcessA" ascii
        $c2 = "CreateProcessW" ascii
        $c3 = "WinExec" ascii
        $c4 = "system(" ascii
    condition:
        uint16(0) == 0x5A4D and any of ($c*)
}

/* End of file */
